---

- name: Download emacs dotfiles
  git: repo=https://github.com/antonshwab/emacs-dotfiles.git
       dest=~
       force=yes
  tags: ['emacs']

- name: Move emacs dotfiles to .emacs.d
  command: mv ~/emacs-dotfiles ~/.emacs.d
  tags: ['emacs']

- name: Create ~/.config
  file: path=~/.config
        state=directory

- name: Symlink karabiner config
  file: src=~/dotfiles/files/karabiner
        dest=~/.config
        state=link
        force=yes

- name: Symlink rest dotfiles
  file: src=~/dotfiles/files/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .gitignore
    - .bashrc
    - .bash_profile
