---

- name: Create .config
  file:
    path: ~/.config
    state: directory
  tags: ['dotfiles']

- name: Symlink karabiner config
  file:
    src: ~/dotfiles/files/karabiner
    dest: ~/.config/karabiner
    state: link
    force: yes
  tags: ['dotfiles']

- name: Symlink dotfiles
  file:
    src: "./files/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
  become: no
  with_items: "{{ dotfiles_files }}"
  tags: ['dotfiles']
