---

- name: Download emacs dotfiles
  git:
    repo: "{{ emacs_dotfiles_repo }}"
    dest: ~
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
    force: yes
  tags: ['emacs']

- name: Move emacs dotfiles to .emacs.d
  command: mv ~/emacs-dotfiles ~/.emacs.d
  tags: ['emacs']
